[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18.16.0"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"
  NODE_ENV = "production"
  NETLIFY_USE_YARN = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "no-cache"
    Pragma = "no-cache"
